### PR TITLE
Performance tuning

### PR DESCRIPTION
**Pull request by zeebo**
Here's the overall benchcmp output from the changes. It mostly improves things for small k when more work is done per update due to the buffers being smaller.

```
name              old time/op    new time/op    delta
AddNormal_1-8        291ns ± 2%      55ns ± 1%   -81.09%         (p=0.000 n=12+9)
AddNormal_5-8        288ns ± 1%      55ns ± 1%   -80.89%        (p=0.000 n=12+10)
AddNormal_10-8       284ns ± 2%      56ns ± 2%   -80.40%         (p=0.000 n=12+9)
AddNormal_100-8      240ns ± 1%      75ns ± 2%   -68.96%        (p=0.000 n=12+10)
AddNormal_1000-8     151ns ± 1%     143ns ± 0%    -5.24%         (p=0.000 n=10+8)

name              old alloc/op   new alloc/op   delta
AddNormal_1-8        31.0B ± 0%     0.0B ±NaN%  -100.00%        (p=0.000 n=13+10)
AddNormal_5-8        31.0B ± 0%     0.0B ±NaN%  -100.00%        (p=0.000 n=13+10)
AddNormal_10-8       31.0B ± 0%     0.0B ±NaN%  -100.00%        (p=0.000 n=13+10)
AddNormal_100-8      26.0B ± 0%      5.0B ± 0%   -80.77%        (p=0.000 n=13+10)
AddNormal_1000-8     2.00B ± 0%     2.00B ± 0%      ~     (all samples are equal)
```

---

This change is [Reviewable](https://reviewable.io/reviews/dgryski/go-kll/2)

### CODE REVIEW

**Comment by sasha-s** [comment]
maybe update gob serialization for coin?

---

Reviewed 2 of 5 files at r1.
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

_[coin.go, line 16 [r1]](https://reviewable.io:443/reviews/dgryski/go-kll/2#-KOux3NIwwnSvF5zeb65:-KOux3NIwwnSvF5zeb66:by9v4ff) ([raw file](https://github.com/dgryski/go-kll/blob/c67b83da5af289b17e5f3c5d91912673a66acc5e/coin.go#L16)):_

> ``` Go
> // to the random number generator.
> type coin struct {
>   st   uint64
> ```

You could make it smaller with

```
st uint64
mask uint64
```

mask starts with 1
and then shift the mask to the left

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/dgryski/go-kll/2#-:-KOuxSpIuY9nwl5smuFK:b-s2j321)_

**Comment by sasha-s** [comment]
Reviewed 3 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/dgryski/go-kll/2)_

**Comment by zeebo** [comment]
it didn't have that property before (it always used "math/rand".Intn(2) and didn't attempt to save the state).

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[coin.go, line 16 [r1]](https://reviewable.io:443/reviews/dgryski/go-kll/2#-KOux3NIwwnSvF5zeb65:-KOvHqLPOmad_yTRzfKi:b-896fix) ([raw file](https://github.com/dgryski/go-kll/blob/c67b83da5af289b17e5f3c5d91912673a66acc5e/coin.go#L16)):_
<details><summary>

<i>Previously, sasha-s wrote…</i></summary>



> You could make it smaller with
> 
> ```
> st uint64
> mask uint64
> ```
> 
> mask starts with 1
> and then shift the mask to the left
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/dgryski/go-kll/2#-:-KOvHsgLOKQ1ZfLFC1K4:bfmce57)_

**Comment by sasha-s** [comment]
What would happen if someone does

```
var s kll.Sketch
s.UnmarshalBinary(...)   // or gob.xxxx
```

?
It seems that the coin would be in zero state, which would lead to state being zero forever.

Maybe add newCoin to UnmarshalBinary?

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/dgryski/go-kll/2#-:-KOvIxO7NEfjtqPwYO2b:b-xdyw3o)_

**Comment by zeebo** [comment]
Good point. I can either do that or have the coin implementation pick a random state if the state is zero on the call to toss. The latter seems more robust because you don't have to worry about a coin just returning zero forever. What do you think?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/dgryski/go-kll/2#-:-KOvKegj1Pfwy6L1rliu:byd3qvq)_

**Comment by sasha-s** [comment]
I am fine with either.
As Damien pointed out, it should not get into a zero state from a non-zero state.
on the other hand, an extra if in xorshift would most certainly  have a negligible impact on performance and it looks a bit cleaner.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/dgryski/go-kll/2#-:-KOvLI7mWHt6CM9a_dmU:b-135z81)_

**Comment by sasha-s** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/dgryski/go-kll/2)_

**Comment by sasha-s** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/dgryski/go-kll/2#-:-KOvORUnhk8_rDUisiLo:bnfp4nl)_

**Comment by sasha-s** [comment]
Reviewed 2 of 2 files at r4.
Review status: 4 of 6 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/dgryski/go-kll/2)_

**Pull request merged**
